language: swift
osx_image: xcode10
script: make ci
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - make lint
before_deploy:
  - carthage build --no-skip-current
  - carthage archive XCTestTemp
notifications:
  irc: "chat.freenode.net#thepotionlab-notifications"
deploy:
  provider: releases
  api_key:
    secure: HT+ITSoT5hDtqJ+EBiAnh4XHaKrp/aDglNfE/kv4jVxUI4BR1bo881MDnc/SNW7Ld2qhTQ5noFmcOWkLuNFlpuviMxhEbCa7q6EylS2C8KRD3gCTPM3ZdX6ZfekraP1aMe1bR2/PAsxPgj6u7i8YfKgs0uEA9pKHWnrqbB1NGPHsb5Txl4IrB7zgIlexfYtPMZnZ/ghHFR1/90/pZnP45adgx74Jr7Ml+d7vXWFUrdRa2RSQCvZQsJjxiN6PuLCR5ym/ZdLz8DPrcCOkl3oVOQ52LCUmRNr3aur4OBiTW76PDIa1fmYVqyiU3YJ1MabjvCfVwWB/tkJl7M4IzJrAm+xW5x6pbOFmeydKVrUaT3pn5XH+xb/C/215gvT6OlLIy+Q0BHB+8kiQ9hkOLajSL5dphm+UETacs/nSY9T65UeincJpdEQdxXkdSmmoE3lWftjAfxmNxcj6mzAb0Pu9ZUtuj42d1y8XGOrARwFQvORb5qkUPeki5ur4vuKz2sBNCByiPkTMLgEUidmS33F4smX2/6NN/P0pUb+W+xFxoNPeSnvsnA+Q0PetGudz+GA54FvNYr7IPMi321nPA7XKjUjpIGgl7UqGsU3t7Y9VKQSwVHG88KELEtBim6pi4o3QwFC9arQumJcPOPGU2860bvk5jeP8ZIAT08bXdjSeVJ8=
  file: XCTestTemp.framework.zip
  skip_cleanup: true
  on:
    repo: robenkleene/XCTestTemp
    tags: true
